language: erlang
script  : "./rebar get-deps compile && ./rebar skip_deps=true eunit suites=forseti_leader_test && ./rebar skip_deps=true eunit suites=forseti_mnesia_test && ./rebar skip_deps=true eunit suites=forseti_locks_test"
otp_release:
   - 17.0
   - 17.1
   - 17.4
   - R16B01
   - R16B02
   - R16B03-1
notifications:
  slack:
    secure: R/DFvrTxdCqOtfQ9Fp9x21Dsd74nltDk98LR8Gq/hydJIR8IC6I62b8XLje74YFb0yjtXc6v3AIrZAu8WuLDn6fij+yGV0nRy4z3pZA2Sq9qN1QEZ2MYpRJWy36ZU4qf/ST3ZcUArIQr7hGslpSEJy7f6PhKajcU/5p97Ps3k2s=

