language: erlang
sudo: false
script: "./rebar get-deps compile && ./rebar skip_deps=true eunit"
otp_release:
   - 19.3
   - 19.2
   - 19.1
   - 19.0
   - 18.3
   - 18.2.1
   - 18.2
   - 18.1
   - 18.0
   - 17.5
   - 17.4
   - 17.1
   - 17.0
   - R16B03-1
   - R16B02
   - R16B01
notifications:
  slack:
    secure: R/DFvrTxdCqOtfQ9Fp9x21Dsd74nltDk98LR8Gq/hydJIR8IC6I62b8XLje74YFb0yjtXc6v3AIrZAu8WuLDn6fij+yGV0nRy4z3pZA2Sq9qN1QEZ2MYpRJWy36ZU4qf/ST3ZcUArIQr7hGslpSEJy7f6PhKajcU/5p97Ps3k2s=

