language: erlang
script  : "./rebar get-deps compile && ./rebar skip_deps=true eunit"
otp_release:
   - R15B01
   - R15B02
   - R15B03
   - R16B
   - R16B01
   - R16B02
   - R16B03
   - R16B03-1
   - 17.0-rc1

